alias e='exit'
alias c='clear'
alias p='ipython3'
alias als='vim ~/.bash_aliases'
alias sals='source ~/.bash_aliases'
alias ff='firefox'
alias bn='~/tools/binaryninja/binaryninja & disown'
alias t='tmux'
alias ga='git add'
alias gc='git commit -m"$*"'
alias gp='git push'
alias po='poweroff'
alias m='vlc --random *.mp3 & disown'

